---
charts:
  - limesurvey
  - ejabberd
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
debug: false
remote: origin
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
