{{- if .Values.certificate.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ejabberd.certificateSecretName" . }}
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
spec:
  dnsNames:
    {{- toYaml .Values.config.hosts | nindent 4 }}
  issuerRef:
    {{- toYaml .Values.certificate.issuerRef | nindent 4 }}
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: {{ include "ejabberd.certificateSecretName" . }}
  usages:
  - server auth
{{- end }}
