apiVersion: v1
kind: Service
metadata:
  name: {{ include "ejabberd.fullname" . }}
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5222
      targetPort: xmpp-c2s
      protocol: TCP
      name: xmpp-c2s
    - port: 5269
      targetPort: xmpp-s2s
      protocol: TCP
      name: xmpp-s2s
    - port: 5443
      targetPort: http
      protocol: TCP
      name: http
    - port: 5280
      targetPort: admin-http
      protocol: TCP
      name: admin-http
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "ejabberd.selectorLabels" . | nindent 4 }}
